name: Publish

on:
  release:
    # We run this workflow when a new GitHub release is created
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the release artifacts of the library
      - name: Release build
        # assembleRelease for all modules, excluding non-library modules: samples, docs
        run: ./gradlew assembleRelease :android-view-lifecycle:assembleRelease
        # -x :sample1:assembleRelease -x :sample2:assembleRelease

      # Generates other artifacts
      - name: Source jar and dokka
        run: ./gradlew androidSourcesJar javadocJar

      # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
        #closeAndReleaseSonatypeStagingRepository
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}